version: "3.8"
networks:
  proxy6:
    external: true
    
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 80:8000
    image: app:django
    container_name: shell_plus
    command: python manage.py runserver 0.0.0.0:8000
